build-frontend-container-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/src/frontend"
      --dockerfile "${CI_PROJECT_DIR}/src/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:frontend"

build-beverage-service-container-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/src/backend/beverageService"
      --dockerfile "${CI_PROJECT_DIR}/src/backend/beverageService/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:beverageService"

build-defrosting-service-container-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/src/backend/defrostingService"
      --dockerfile "${CI_PROJECT_DIR}/src/backend/defrostingService/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:defrostingService"

build-popcorn-service-container-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/src/backend/popcornService"
      --dockerfile "${CI_PROJECT_DIR}/src/backend/popcornService/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:popcornService"

build-potato-service-container-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/src/backend/potatoService"
      --dockerfile "${CI_PROJECT_DIR}/src/backend/potatoService/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:potatoService"
